chore: remove ie 11 support
videojs/vhs-utils pull request #34
Opened 2022-08-10 16:09 UTC by kchang-brightcove

Removed IE 11 support

2022-08-16 17:56 UTC, misteroneill requested changes
It looks like this is still running tests against Safari 9 and failing because it doesn't recognize `const`. We should change the browsers it runs tests against.

2022-08-16 18:34 UTC, gkatsev commented
> It looks like this is still running tests against Safari 9 and failing because it doesn't recognize `const`. We should change the browsers it runs tests against.

I think updating to [videojs-generate-karma-config@8.0.1](https://github.com/videojs/videojs-generate-karma-config) will fix that.

2022-08-18 19:06 UTC, alex-barstow approved these changes

2022-08-19 14:13 UTC, misteroneill approved these changes

2022-08-19 14:14 UTC, merged